# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: csharp
mono:
 - latest

os:
 - osx
 - linux

env:
 global:
  - MONO_OPTIONS=--debug

install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore LibGit2Sharp.sln

before_install:
 - date -u
 - uname -a
 - env | sort

solution: LibGit2Sharp.sln

# Build libgit2, LibGit2Sharp and run the tests
script:
 - ./build.libgit2sharp.sh 'LEAKS_IDENTIFYING'

# Only watch the development branch
branches:
 only:
   - master
   - /^maint.*/

# Notify of build changes
notifications:
 email:
  - emeric.fermas@gmail.com
